# Generated by Django 5.0.6 on 2024-06-16 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Carrera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=80)),
                ("status", models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=80)),
                ("ap_pat", models.CharField(max_length=80)),
                ("ap_mat", models.CharField(max_length=80)),
                ("usu", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=20)),
                ("fecha_nac", models.DateField()),
                ("status", models.SmallIntegerField()),
                (
                    "carrera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="chat.carrera"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mensaje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("txt_mensaje", models.TextField()),
                ("status", models.SmallIntegerField()),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="chat.persona"
                    ),
                ),
            ],
        ),
    ]
