# Generated by Django 5.0.6 on 2024-06-16 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="persona",
            name="password",
        ),
        migrations.AddField(
            model_name="persona",
            name="pass_field",
            field=models.CharField(default="default_password", max_length=80),
        ),
        migrations.AlterField(
            model_name="mensaje",
            name="persona",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="chat.persona"
            ),
        ),
        migrations.AlterField(
            model_name="persona",
            name="usu",
            field=models.CharField(max_length=80),
        ),
    ]
